#!/bin/sh

set -eu

git remote show | grep -qw upstream || git remote add upstream git://git.postgresql.org/git/postgresql.git
git checkout -q master
git remote update
git merge -q --ff-only upstream/master

for branch in $(git branch -r | grep cfpatch-); do
	printf "\n# $branch\n"
	git merge -q --no-commit --no-ff $branch
	git reset -q --hard
done
