#!/bin/sh

set -eu

cd "$(git rev-parse --show-toplevel)"

if [ ! -e .git/info/attributes ]; then
	cat <<EOF >.git/info/attributes
catversion.h	merge=union
EOF
fi

git remote show | grep -qw upstream || git remote add upstream git://git.postgresql.org/git/postgresql.git
git checkout -q master
git remote update --prune >/dev/null
git merge -q --ff-only upstream/master

i=0
for branch in $(git branch -r | grep cfpatch-); do
	i=$(($i + 1))

	if out=$(git merge -q --no-commit --no-ff $branch 2>&1); then
		echo "ok $i $branch"
	else
		echo "not ok $i $branch"
		echo "$out" | sed -n '/CONFLICT/s/^/    # /p'
	fi
	git reset -q --hard
done

echo "1..$i"
